image_scraper/urls.py
"""Defines URL patterns for the main_site."""

from django.conf.urls import url

from . import views

app_name = 'image_scraper'

urlpatterns = [
    # Home page
    url(r'^stories/$', views.stories, name='stories'),
]

main_site/urls.py
"""Defines URL patterns for the main_site."""

from django.conf.urls import url

from . import views

app_name = 'main_site'

urlpatterns = [
    # Home page
    url(r'^$', views.index, name='index'),
    #Individual entry page
    url(r'^entries/(?P<entry_id>\d+)/$', views.entry, name='entry'),
    #Page for adding a new entry
    url(r'^new_topic/$', views.new_entry, name='new_entry'),
    #Page for editing an existing entry
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
    #Python projects page
    url(r'^python/$', views.pyprojects, name='pyprojects'),
    #Javascript projects page
    url(r'^javascript/$', views.jsprojects, name='jsprojects'),
    #Page for adding a new programming entry
    url(r'^new_code_entry', views.new_code_entry, name='new_code_entry'),
    #Page for editing an existing code entry
    url(r'^edit_code_entry/(?P<code_entry_id>\d+)/$', views.edit_code_entry, name='edit_code_entry'),
    #Individual project entry page
    url(r'^code_entries/(?P<code_entry_id>\d+)/$', views.code_entry, name='code_entry'),
    #Vue project (need to move things like this to their own app.)
    url(r'^to-do/$', views.to_do, name="to_do")
]

personal_website/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main_site.urls')),
    url(r'', include('image_scraper.urls')),
]

image_scraper/models.py
from django.db import models

# Create your models here.

main_site/models.py
from django.db import models

# Create your models here.

class Entry(models.Model):
    """An entry on the front page of the website."""
    date_added = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=108)
    text = models.TextField()

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        if len(self.text) > 50:
            return self.text[:50] + "..."
        else:
            return self.text

class CodeEntry(models.Model):
    """An entry on the programming pages of the website."""
    JAVASCRIPT = 'JS'
    PYTHON = 'PYTHON'

    date_added = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=108)
    LANGUAGE_CHOICES = (
        (JAVASCRIPT, 'Javascript'),
        (PYTHON, 'Python'),
    )
    language = models.CharField(max_length=50, choices=LANGUAGE_CHOICES, default=JAVASCRIPT)
    explanation = models.TextField()
    notes = models.TextField(blank=True)
    attempt = models.TextField()
    goal = models.TextField()

    class Meta:
        verbose_name_plural = 'code_entries'
    
    def __str__(self):
        """Return a string representation of the model."""
        return self.explanation

main_site/forms.py
from django import forms

from .models import Entry, CodeEntry

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['title', 'text']
        
class CodeEntryForm(forms.ModelForm):
    class Meta:
        model = CodeEntry
        fields = ['title', 'language', 'explanation', 'notes', 'attempt', 'goal']

image_scraper/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

def stories(request):
    return render(request, 'image_scraper/home.html')

main_site/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Entry, CodeEntry
from .forms import EntryForm, CodeEntryForm

def index(request):
    """The home page for the site."""
    index_entries = Entry.objects.order_by('-date_added')
    code_entries = CodeEntry.objects.order_by('-date_added')
    entries = list(index_entries) + list(code_entries)
    entries.sort(key=lambda x: x.date_added, reverse=True)
    context = {'entries':entries}
    return render(request, 'main_site/index.html', context)

def entry(request, entry_id):
    """A single entry."""
    entry = Entry.objects.get(id=entry_id)
    context = {'entry':entry}
    return render(request, 'main_site/entry.html', context)

def new_entry(request):
    """Add a new entry."""
    if request.method != 'POST':
        #No data submitted; create a blank form.
        form = EntryForm()
    else:
        #POST data submitted; create a blank form.
        form = EntryForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main_site:index'))
    
    context = {'form':form}
    return render(request, 'main_site/new_entry.html', context)

def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    
    if request.method != 'POST':
        #Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        #POST data submitted; process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main_site:entry', args=[entry.id]))
    
    context = {'entry':entry, 'form':form}
    return render(request, 'main_site/edit_entry.html', context)

def pyprojects(request):
    code_entries = CodeEntry.objects.order_by('-date_added')
    context = {'code_entries':code_entries}
    return render(request, 'main_site/python.html', context)

def jsprojects(request):
    code_entries = CodeEntry.objects.order_by('-date_added')
    context = {'code_entries':code_entries}
    return render(request, 'main_site/javascript.html', context)

def code_entry(request, code_entry_id):
    code_entry = CodeEntry.objects.get(id=code_entry_id)
    context = {'code_entry':code_entry}
    return render(request, 'main_site/code_entry.html', context)

def new_code_entry(request):
    """Add a new code entry."""
    if request.method != 'POST':
        #No data submitted; create a blank form.
        form = CodeEntryForm()
    else:
        #POST data submitted; create a blank form.
        form = CodeEntryForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main_site:index'))
    
    context = {'form':form}
    return render(request, 'main_site/new_code_entry.html', context)

def edit_code_entry(request, code_entry_id):
    """Edit an existing code entry."""
    code_entry = CodeEntry.objects.get(id=code_entry_id)

    if request.method != 'POST':
        #Initial request; pre-fill form with the current entry.
        form = CodeEntryForm(instance=code_entry)
    else:
        #POST data submitted; process data.
        form = CodeEntryForm(instance=code_entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main_site:code_entry', args=[code_entry.id]))

    context = {'code_entry':code_entry, 'form':form}
    return render(request, 'main_site/edit_code_entry.html', context)

def to_do(request):
    return render(request, 'main_site/to-do.html')

image_scraper/templates/image_scraper/base.html
{% load bootstrap3 %} {% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, intial-scale=1">
    <title>Borrowed Stories</title>
    <LINK REL=StyleSheet HREF="{% static 'css/main.css' %}" TYPE="text/css" MEDIA=screen>
    {% bootstrap_css %} {% bootstrap_javascript %}
</head>

<body>
    <div class="container-fluid text-center" id="main-body">
            <div class="row content" id="inner-body">
                <div class="col-sm-3 sidenav" id="left-section">
                    {% block leftcontent %} {% endblock leftcontent %}
                </div>
                <div class="col-sm-9" id="right-section">
                    {% block rightcontent %} {% endblock rightcontent %}
                </div>
            </div>
        </div>
</body>

image_scraper/templates/image_scraper/home.html
{% extends "image_scraper/base.html" %}
{% load static %}
<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.0.3/vue.js"></script>        
    <LINK REL=StyleSheet HREF="{% static 'css/home.css' %}" TYPE="text/css" MEDIA=screen>
</head>

{% block leftcontent %}
    <h4>This is the left content section.</h4>
{% endblock leftcontent %}

{% block rightcontent %}
    <div class="container" id="todo">
        <section class="panel">
            <input type="checkbox" id="mark-all">
            <input type="text" placeholder="What do you need to do?" autofocus class="text-input">
            <button>Clear List</button>
        </section>

        <ul class="list">
            <li>
                <input type="checkbox" class="checkbox">
                <input type="text" class="text-input">
                <label for="checkbox"></label>
                <button class="delete">X</button>
            </li>
        </ul>
    </div>
{% endblock rightcontent %}

main_site/templates/main_site/base.html
{% load bootstrap3 %} {% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, intial-scale=1">

    <title>Lapine Dreams</title>
    <script src="{% static 'js/main.js' %}"></script>
    <LINK REL=StyleSheet HREF="{% static 'css/main.css' %}" TYPE="text/css" MEDIA=screen> {% bootstrap_css %} {% bootstrap_javascript %}
</head>

<body onload="updateNav();">
    <nav class="navbar navbar-inverse" id="main-nav">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'main_site:index' %}">Logo</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'main_site:index' %}" class="current">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'main_site:pyprojects' %}">Python</a>
                    </li>
                    <li>
                        <a href="{% url 'main_site:jsprojects' %}">Javascript</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container-fluid text-center" id="actual-body">
        <div class="row content" id="actual-inner-body">
            <div class="col-sm-2 sidenav" id="left-section">
                {% block leftcontent %} {% endblock leftcontent %}
            </div>
            <div class="col-sm-8 text-left" id="main-section">
                {% block content %} {% endblock content %}
            </div>
            <div class="col-sm-2 sidenav" id="right-section">
                {% block rightcontent %} {% endblock rightcontent %}
            </div>
        </div>
    </div>

    <footer class="container-fluid text-center" id="main-footer">
        <p>&#128048</p>
    </footer>
</body>

</html>

main_site/templates/main_site/code_entry.html
{% extends "main_site/base.html" %}
{% load bootstrap3 %} {% load static %}
{% bootstrap_css %} {% bootstrap_javascript %}


{% block content %}
<head>
    <LINK REL=StyleSheet HREF="{% static 'css/index.css' %}" TYPE="text/css" MEDIA=screen>
</head>

<body>
    <div id = "entry_container">
            <div class = "index_entry">
                <h4> {{ code_entry.title }} - {{ code_entry.date_added}} </h4>
                {% if code_entry.explanation %}
                    <p><b>Explanation:<br></b>
                    {{ code_entry.explanation }}</p>
                {% endif %}
                {% if code_entry.notes %}
                    <p><b>Notes:<br></b>
                    {{ code_entry.notes }}</p>
                {% endif %}
                <p><b>My attempt:<br></b></p>
                    <pre>{{ code_entry.attempt }}</pre>
                <br>
                <p><b>What I would use in practice:<br></b></p>
                    <pre>{{ code_entry.goal }}</pre>
            </div>
    </div>
</body>
{% endblock content %}

main_site/templates/main_site/edit_code_entry.html
{% extends "main_site/base.html" %}

{% block content %}
    <p>Edit entry:</p>

    <form action="{% url 'main_site:edit_code_entry' code_entry.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save Changes</button>
    </form>
{% endblock content %}

main_site/templates/main_site/edit_entry.html
{% extends "main_site/base.html" %}

{% block content %}
    <p>Edit entry:</p>

    <form action="{% url 'main_site:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save Changes</button>
    </form>
{% endblock content %}

main_site/templates/main_site/entry.html
{% extends "main_site/base.html" %}
{% load bootstrap3 %} {% load static %}
{% bootstrap_css %} {% bootstrap_javascript %}


{% block content %}
<head>
    <LINK REL=StyleSheet HREF="{% static 'css/index.css' %}" TYPE="text/css" MEDIA=screen>
</head>

<body>
    <div id = "entry_container">
            <div class = "index_entry">
                <h4> {{ entry.title }} - {{ entry.date_added}} </h4>
                <p>{{ entry.text }}</p>
            </div>
    </div>
</body>
{% endblock content %}

main_site/templates/main_site/index.html
{% extends "main_site/base.html" %}
{% load bootstrap3 %} {% load static %}
{% bootstrap_css %} {% bootstrap_javascript %}

{% block leftcontent %}
    <p><a href="{% url 'main_site:to_do' %}">To-do List</a></p>
    <p><a href="#">Link</a></p>
    <p><a href="#">Link</a></p>
{% endblock leftcontent %}

{% block content %}
<head>
    <LINK REL=StyleSheet HREF="{% static 'css/index.css' %}" TYPE="text/css" MEDIA=screen>
</head>

<body>
    <div id = "entry_container">
        {% for entry in entries %}
            <div class = "index_entry">
                {% if entry.language %}
                    <a href="{% url 'main_site:entry' entry.id %}">
                        <h4> 
                            {{ entry.title }}
                            <div class="dropdown" id="entry_menu">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                                    <span class="glyphicon glyphicon-option-horizontal"></span>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-right" id="entry_dropdown">
                                    <li><a href="{% url 'main_site:new_code_entry' %}">New</a></li>
                                    <li><a href="{% url 'main_site:edit_code_entry' entry.id %}">Edit</a></li>
                                </ul>
                            </div> 
                        </h4>
                    </a>
                    <p>{{ entry }}</p>
                {% else %}
                    <a href="{% url 'main_site:entry' entry.id %}">
                        <h4> {{ entry.title }}
                            <div class="dropdown" id="entry_menu">
                                <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                                    <span class="glyphicon glyphicon-option-horizontal"></span>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-right" id="entry_dropdown">
                                    <li><a href="{% url 'main_site:new_entry' %}">New</a></li>
                                    <li><a href="{% url 'main_site:edit_entry' entry.id %}">Edit</a></li>
                                </ul>
                            </div> 
                        </h4>
                    </a>
                    <p>{{ entry }}</p>
                {% endif %}
            </div>
        {% empty %}
            <li>Rabbits live in cozy burrows.</li>
        {% endfor %}
    </div>
</body>
{% endblock content %}

{% block rightcontent %}
    <div class="well">
        <p>ADS</p>
    </div>
    <div class="well">
        <p>ADS</p>
    </div>
    <div class="well">
        <p>ADS</p>
    </div>
    <div class="well">
        <p>ADS</p>
    </div>
    <button onclick="adjustSize()">Get Size</button>
{% endblock rightcontent %}

main_site/templates/main_site/javascript.html
{% extends "main_site/base.html" %} 
{% load bootstrap3 %} {% load static %} {% bootstrap_css %} {% bootstrap_javascript %}
{% block content %}

<head>
    <LINK REL=StyleSheet HREF="{% static 'css/index.css' %}" TYPE="text/css" MEDIA=screen>
</head>

<body>
    <div id="entry_container">
        {% for entry in code_entries %} {% if entry.language == 'JS' %}
        <div class="index_entry">
            <a href="{% url 'main_site:code_entry' entry.id %}">
                <h4 title= {{ entry.date_added }}>
                    {{ entry.title }}
                    <div class="dropdown" id="entry_menu">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                            <span class="glyphicon glyphicon-option-horizontal"></span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right" id="entry_dropdown">
                            <li><a href="{% url 'main_site:new_code_entry' %}">New</a></li>
                            <li><a href="{% url 'main_site:edit_code_entry' entry.id %}">Edit</a></li>
                        </ul>
                    </div>            
                </h4>
        </a>
        <p>{{ entry }}</p>
    </div>
        {% endif %} {% empty %}
        <li>Rabbits live in cozy burrows.</li>
        {% endfor %}
    </div>
</body>
{% endblock content %}

main_site/templates/main_site/new_code_entry.html
{% extends "main_site/base.html" %}

{% block content %}
    <p>Add a new code entry:</p>
    <form action="{% url 'main_site:new_code_entry' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add Entry</button>
    </form>
{% endblock content %}

main_site/templates/main_site/new_entry.html
{% extends "main_site/base.html" %}

{% block content %}
    <p>Add a new entry:</p>
    <form action="{% url 'main_site:new_entry' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add Entry</button>
    </form>
{% endblock content %}

main_site/templates/main_site/python.html
{% extends "main_site/base.html" %} 
{% load bootstrap3 %} {% load static %} {% bootstrap_css %} {% bootstrap_javascript %}
{% block content %}

<head>
    <LINK REL=StyleSheet HREF="{% static 'css/index.css' %}" TYPE="text/css" MEDIA=screen>
</head>

<body>
    <div id="entry_container">
        {% for entry in code_entries %} {% if entry.language == 'PYTHON' %}
        <div class="index_entry">
            <a href="{% url 'main_site:code_entry' entry.id %}">
                <h4 title= {{ entry.date_added }}>
                    {{ entry.title }}
                    <div class="dropdown" id="entry_menu">
                        <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                            <span class="glyphicon glyphicon-option-horizontal"></span>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right" id="entry_dropdown">
                            <li><a href="{% url 'main_site:new_code_entry' %}">New</a></li>
                            <li><a href="{% url 'main_site:edit_code_entry' entry.id %}">Edit</a></li>
                        </ul>
                    </div>            
                </h4>
        </a>
        <p>{{ entry }}</p>
    </div>
        {% endif %} {% empty %}
        <li>Rabbits live in cozy burrows.</li>
        {% endfor %}
    </div>
</body>
{% endblock content %}

main_site/templates/main_site/to-do.html
{% load static %}
<head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.0.3/vue.js"></script>
        <link href= "{% static 'css/to_do/index.css' %}" rel="stylesheet" type="text/css" media="all">
    </head>
    <body>
        <!-- Main Div Holding our Application Data -->
    <div class="container" id="todo">
        <!-- Panel for holding our input -->
        <section class="panel">
            <input type="checkbox" id="mark-all" v-bind:checked="areAllSelected" v-on:click="selectAll">
            <input type="text" placeholder="What do you need to do?" autofocus class="text-input" v-model="newTask" v-on:keyup.enter="addTask">
            <button v-on:click="clearList">Clear List</button>
        </section>
        
        <!-- Unorderd list for holding our todo items -->
        <ul class="list">
            <li v-for="task in taskList" v-bind:class="{done: task.checked}">
                <input type="checkbox" class="checkbox" v-model="task.checked">
                <label for="checkbox" >{{ task.text }}</label>
                <button class="delete" v-on:click="removeTask(task)">X</button>
            </li>
        </ul>
        
        </div>
        <script src="{% static 'js/main.js' %}"></script>
        <script src="{% static 'js/to_do/index.js' %}"></script>
    </body>